baseURL = "https://bittukumarray.github.io/"
title = "Bittu Kumar Ray"
theme = "PaperMod"

[params]
  description = "Engineering, Distributed Systems, Databases, Kafka"
  defaultTheme = "dark"
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  mainSections = ["posts", "notes", "system-design", "databases"]

[menu]

  [[menu.main]]
    name = "Blogs"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Notes"
    url = "/notes/"
    weight = 2

  [[menu.main]]
    name = "System Design"
    url = "/system-design/"
    weight = 3

  [[menu.main]]
    name = "Databases"
    url = "/databases/"
    weight = 4
